# Change these first
owner: danielnaoexiste
repo: froggy-status

sites:
  - name: Froggy Bot
    url: froggy-bot.fly.dev
    icon: https://froggy.danielnaoexiste.dev/froggy.ico
  - name: Froggy Web
    url: https://froggy.danielnaoexiste.dev/
  - name: Froggy API
    url: https://froggy-api.danielnaoexiste.dev/api
    icon: https://froggy.danielnaoexiste.dev/froggy.ico

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  baseUrl: /froggy-status
  theme: dark
  logoUrl: https://froggy.danielnaoexiste.dev/froggy.ico
  favicon: https://froggy.danielnaoexiste.dev/froggy.ico
  name: Froggy Status
  introTitle: "**Froggy** is a customizable general purpose discord bot."
  introMessage: Ribbit
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/danielnaoexiste/froggy-status

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
